services:
  transip-domain-catcher:
    image: bjornftw/transip-domain-catcher
    container_name: transip-domain-catcher
    restart: unless-stopped

    environment:
      - TRANSIP_USERNAME=${TRANSIP_USERNAME}
      - TRANSIP_PRIVATE_KEY_FILE=${TRANSIP_PRIVATE_KEY_FILE}
      - TRANSIP_TOKEN_LABEL=${TRANSIP_TOKEN_LABEL}
      - DOMAINS=${DOMAINS}
      - CHECK_INTERVAL_SECONDS=${CHECK_INTERVAL_SECONDS}

    volumes:
      - ./config:/usr/src/app/config
      - ./logs:/usr/src/app/logs
