services:
  transip-domain-catcher:
    build:
      context: .
      dockerfile: Dockerfile

    image: i-lynx/transip-domain-catcher:latest

    container_name: transip-domain-catcher
    restart: unless-stopped
    environment:
      - TRANSIP_USERNAME=${TRANSIP_USERNAME}
      - TRANSIP_PRIVATE_KEY_FILE=${TRANSIP_PRIVATE_KEY_FILE}
      - TRANSIP_TOKEN_LABEL=${TRANSIP_TOKEN_LABEL}
      - DOMAINS=${DOMAINS}
      - CHECK_INTERVAL_SECONDS=${CHECK_INTERVAL_SECONDS}

      - NOTIFICATION_ENABLED=${NOTIFICATION_ENABLED}
      - NOTIFICATION_PROVIDER=${NOTIFICATION_PROVIDER}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./config:/usr/src/app/config
      - ./logs:/usr/src/app/logs
